### PR TITLE
Resolves Error while using projector

### PR DESCRIPTION
**Pull request by ZohebAbai**
Since the new major release of Bokeh version 3.0, the `plot_width` (and `plot_height`) properties have been removed. These have been replaced by standard `width` and `height` for all layout-able models according to [Migration Guide](https://github.com/bokeh/bokeh/wiki/Migration-Guides#300). The minor update fixes the error generated while using the `projector`. A recent closed issue in the official Bokeh Repository can be found [here](https://github.com/bokeh/bokeh/issues/12543). The update was successfully tested in [a notebook](https://nbviewer.org/github/ZohebAbai/Deep-Learning-Projects/blob/master/05_TF_Metric_Learning.ipynb).

### CODE REVIEW

**Review by owenvallis — APPROVED** [review]

**Comment by owenvallis** [comment]
Thanks for the PR!

**Comment by owenvallis** [comment]
Looks like  a large number of mypy errors in the tests. These seem to be in files that are not touched by this change so I'm assuming this is a change in mypy. I'll try and fix these locally and push any changes to the dev branch.

**Comment by ZohebAbai** [comment]
Happy to contribute. Thanks.

**Comment by owenvallis** [comment]
I pushed my local changes and all mypy errors should be fixed once you merge in the latest dev updates.

**Comment by ZohebAbai** [comment]
Merged.

**Comment by owenvallis** [comment]
looks like the failing tests are just some complaints from the Black and Isort formatters. I'll merge and address the formatting issue in my local branch.

**Pull request merged**
