### PR TITLE
Add MultiShotFileSampler

### PR DESCRIPTION
**Pull request by AminHP**
The `MultiShotFileSampler` is a sampler class for reading data from image files stored on the disc. It is quite similar to the `MultiShotMemorySampler`. However, `MultiShotMemorySampler` reads data from an array in the memory, while `MultiShotFileSampler` loads image files from the disc using their corresponding file address. Note that the `x` argument in the class is filled with the file path of the images.

This feature is useful when our dataset is available as multiple images stored on the disk and we don't want to get into trouble of creating *TFRecords*.

### CODE REVIEW

**Comment by AminHP** [comment]
It's been a week since I created this PR. I would appreciate it if you could check it out and give your opinion. @owenvallis

**Comment by owenvallis** [comment]
Hi Amin, thanks for the PR. This will be helpful to simplify some of the example notebooks.

Can you update this PR to merge into the Development branch?

**Comment by owenvallis** [comment]
Thanks again for the PR, as I mentioned I think this will be very useful. However, one concern is this duplicates a lot of the code from the MultiShotMemorySampler and I'm worried about the code diverging over time. I think there is likely a way to refactor the Memory samplers to support providing a custom reader function, e.g., images in this case and an in memory read for the existing version. 

Seems like we can update the MultiShotMemorySampler with your changes using a general example_load_fn that defaults to just `lambda x: x`. Then we can pass the image_load function for your image case.

wdyt?

**Comment by AminHP** [comment]
Thanks for the quick reply @owenvallis . I updated the PR.

**Comment by AminHP** [comment]
> 

That would be great, I agree with you. I've had the same concern but I thought changing MemorySampler might create some other issues with the other files in the repo.

**Comment by AminHP** [comment]
I will work on the refactoring and push some new commits in a few days.

**Comment by owenvallis** [comment]
SG. We can merge this into Dev and then I can look at combining them before the next update to master. I think we can make the change to MultiShotMemorySampler without breaking existing usage, but I'll dbl check.

**Comment by AminHP** [comment]
Nice 👍

**Comment by AminHP** [comment]
I pushed some new changes. Please check them out @owenvallis .

**Comment by owenvallis** [comment]
Thanks for the quick refactor, the changes look good. Seems like there is just a typing issue from mypy. 

```
tensorflow_similarity/samplers/file_samplers.py:40: error: Returning Any from function declared to return "FloatTensor"  [no-any-return]
tensorflow_similarity/samplers/file_samplers.py:40: error: Returning Any from function declared to return "IntTensor"  [no-any-return]
```

I'll merge the changes and update the typing on my side.

Thanks again for the PR.

**Comment by AminHP** [comment]
Thanks for creating and maintaining this great library. It was very helpful for me and saved a lot of my time.

**Pull request merged**
