### PR TITLE
Fixed typo in slice id

### PR DESCRIPTION
**Pull request by abhisharsinha**

### CODE REVIEW

**Comment by owenvallis** [comment]
Thanks for catching this.

**Comment by abhisharsinha** [comment]
@owenvallis Hi, I believe there was a typo here which was accessing an undefined variable. Can you please check this out?

**Comment by owenvallis** [comment]
> @owenvallis Hi, I believe there was a typo here which was accessing an undefined variable. Can you please check this out?

Looks like I didn't update the start_idx

**Comment by owenvallis** [comment]
Looks good, thanks again for the PR.

**Pull request merged**
