### PR TITLE
fix: TensorFlow spelling error in README

### PR DESCRIPTION
**Pull request by Agrover112**
Fixed spelling error for TensorFLow----> TensorFlow

### CODE REVIEW

**Comment by Agrover112** [comment]
@googlebot I signed it!

**Comment by Agrover112** [comment]
@owenvallis

**Comment by owenvallis** [comment]
Thanks @agrover112, can you also increment the patch number in tensorflow_similarity/__init__.py.

thanks,

**Comment by Agrover112** [comment]
> Thanks @Agrover112, can you also increment the patch number in tensorflow_similarity/**init**.py.
> 
> thanks,
Sure let me check it out .

**Review by owenvallis — APPROVED** [review]

**Comment by Agrover112** [comment]
Thanks @owenvallis  !

**Pull request merged**
