### PR TITLE
Minor fixing of dead links

### PR DESCRIPTION
**Pull request by dewball345**
A lot of the files were referring to a non-existent `main` branch so switched the links to `master`

### CODE REVIEW

**Comment by dewball345** [comment]
(there are a lot of instances of this so I'm not sure i can correct them all)

**Comment by owenvallis** [comment]
Thanks for catching these. I'll merge the changes in, and I think I also need to take a look at the script we use to build the API docs.

**Comment by dewball345** [comment]
@owenvallis btw not sure if this was intended or not, but noticed that changes were not merged into master. Also saw that they were merged into my fork of this repo(accidentally?)

**Review by owenvallis — APPROVED** [review]

**Comment by owenvallis** [comment]
Hi @dewball345, the changes merged into your branch should just be to sync up with another PR I merged earlier today. Merging these now and then I'll do another update on the Barlow Twins PR to pull in these changes.

**Pull request merged**
