### PR TITLE
0.17rc

### PR DESCRIPTION
**Pull request by owenvallis**
General updates and improvements.

### CODE REVIEW

**Comment by owenvallis** [comment]
Looks like the CLA check is failing on the GitHub Actions. They just bump the dev version, but I don't see an easy way to rewrite the commit history. I'll see if I can update the action to provide a valid email and author moving forward.

**Review by ebursztein — APPROVED** [review]
Collection of fixes from the last year --

**Comment by ebursztein** [comment]
Unknown contributor was a bug -- evertything is passing. Forcing commit.

**Comment by owenvallis** [comment]
Hi @ManafMukred, we were waiting to push a few patches. I just published 0.17.1 and it should be available on pypi now.

**Comment by ManafMukred** [comment]
> Hi @ManafMukred, we were waiting to push a few patches. I just published 0.17.1 and it should be available on pypi now.

Thanks, I just checked now.

Just out of curiosity :),  Will there be more contrastive and non-contrastive (like BYOL) algorithms added into _tfsim_  soon?

**Pull request merged**
